# Generated by Django 5.0.3 on 2024-04-01 09:26

from django.db import migrations, models
import uuid


def generate_unique_order_numbers(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    existing_orders = Order.objects.all()

    for order in existing_orders:
        if not order.order_number:
            order.order_number = uuid.uuid4()
            order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_zarinpal_authority_order_zarinpal_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.RunPython(generate_unique_order_numbers),
    ]
