# Generated by Django 5.0.3 on 2024-03-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
