# Generated by Django 5.0.3 on 2024-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_description_alter_product_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_cover',
            field=models.ImageField(default=1, upload_to='cover/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
